name: Take Screenshot Action

on:
  push:
    branches: [main]

jobs:
  take-screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: touch file.txt
      - run: git config --local user.name "oelgazzar"
      - run: git config --local user.email "omelgazzar@gmail.com"
      - run: git add -A
      - run: git commit -m "commit message"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
            force_with_lease: true
