name: Take Screenshot Action

on:
  push:
    branches: [main]

jobs:
  take-screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: touch file.txt
      - run: git config --local user.name "oelgazzar"
      - run: git config --local user.email "omelgazzar@gmail.com"
      - run: git add -A
      - run: git commit -m "commit message"
      - run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/oelgazzar/alpaca
      - run: git push
